### ISSUE TITLE
安装过程中遇到的一些问题

### ISSUE THREAD

**Issue by kuye-kuye** [kuaifan/wookteam#1]
您好，很感激您能提供一个如此优秀便利的工具。在安装的过程中，安装您提供的安装教程，在进行到
`composer install` 的时候出现问题，好像是因为php.ini什么的问题，由于没有接触过php的环境，所以在安装这个项目时，遇到很多很多php环境的问题，目前尚不明确php环境是否符合该项目的要求。能麻烦您提供一份更详细的安装教程，或者docker镜像吗？不胜感激！

**Comment by kuaifan** [comment]
会尽快出更详细教程。
