### ISSUE TITLE
关于知识库的一些建议

### ISSUE THREAD

**Issue by ICEORY** [kuaifan/wookteam#11]
1. 能否直接从本地复制粘贴图片到文档中？貌似目前图片只能通过上传的方式插入；

2. 知识库新建文件时，偶尔会出现同时新建多个（2~3个）同样名称的文件，可能是鼠标点击确定按键时多次触发？

3. 知识库能否增加搜索功能？

4. 知识库markdown能否直接导出为md文件？

谢谢！

**Comment by kuaifan** [comment]
感谢支持，支持直接复制粘贴的

**Comment by kuaifan** [comment]
2、3、4已经计划

**Comment by kuaifan** [comment]
2、3、4新版已支持

**Comment by ICEORY** [comment]
感谢~
