### ISSUE TITLE
Illegal use of timeline component (gantt-schedule-timeline-component)

### ISSUE THREAD

**Issue by neuronetio** [kuaifan/wookteam#14]
Hi,
I've noticed that you are using gantt-schedule-timeline-component without proper license.
If you want to use components that are licensed under AGPL-3.0 you whole system must be under the same license (not MIT), otherwise you need to purchase commercial license.
Please contact me at neuronet.io@gmail.com
Thanks

**Comment by kuaifan** [comment]
AGPL-3.0 和MIT区别大吗？




---Original---

**Comment by kuaifan** [comment]
Hi,
First of all, thank you for providing gantt-schedule-timeline-component, wookteam is also an open source product, of course we are also willing to use AGPL-3.0 agreement.
Thanks

**Comment by neuronetio** [comment]
ok, everything is ok now. thanks

**Comment by neuronetio** [comment]
There is another problem.
You are using this component in closed source ENTERPRISE edition which is not under AGPL-3.0 and publicly available code.
Please respond urgently.

**Comment by kuaifan** [comment]
Those who use schedule-timeline-component are all open source. If you still have questions about this, I can give up using schedule-timeline-component.



---Original---

**Comment by kuaifan** [comment]
没有，使用schedule-timeline-component的全部都开源



---Original---

**Comment by neuronetio** [comment]
So stop using this component or pay for commercial license. Open source doesn't always mean free. It is open source but licensed under the AGPL-3.0 license - read the licenses carefully. Everyone has to pay bills and eat something. If you use it in free software then ok, you can use it for free as well, but if you use it and get paid for it you have to pay - I think it's okay. I will not argue with you about what is open source and what is not. Please stop using if you don't understand the terms.

**Comment by kuaifan** [comment]
Since you have said so, you can rest assured that the components you developed have been stopped and schedule-timeline-component will be removed in the next version.




---Original---

**Comment by neuronetio** [comment]
ok, thanks

**Comment by kuaifan** [comment]
The new version `1.5.12` has deleted the gantt-schedule-timeline-calendar component you developed. If you have any questions, please leave a message again.
