### ISSUE TITLE
一些小bug

### ISSUE THREAD

**Issue by zzktz** [kuaifan/wookteam#17]
1、删除未完成的任务。项目未完成数量不变。
2、新增任务，修改计划时间  ，默认会出现。
![图片](https://user-images.githubusercontent.com/45819258/93034852-0b060200-f66e-11ea-8b1b-feb5718a638d.png)
3、系统用起来卡顿，不知道啥原因。

**Comment by kuaifan** [comment]
前两问题很快就可以解决，第三个问题卡是后端卡还是前端卡能否录个视频，视频可发aipaw@qq.com



---原始邮件---
发件人: "zzktz"<notifications@github.com&gt;
发送时间: 2020年9月14日(周一) 上午9:40
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] 一些小bug (#17)




 
1、删除未完成的任务。项目未完成数量不变。
 2、新增任务，修改计划时间  ，默认会出现。
 
 3、系统用起来卡顿，不知道啥原因。

**Comment by zzktz** [comment]
浏览器问题，谷歌的很快，火狐的卡。

**Comment by kuaifan** [comment]
最新提交已经修复。
