### ISSUE TITLE
为什么我部署后，admin账号没有”系统设置"的功能

### ISSUE THREAD

**Issue by Jade999** [kuaifan/wookteam#18]
如题，我在您的https://demo.wookteam.com/演示网站，用账号admin/123456,右上角是可以对网站进行基本的设置的，
但是我部署到服务器上后，右上角却没有“系统设置”这一项，请问这是怎么回事呀

**Comment by kuaifan** [comment]
你可以尝试提供你的安装环境信息给我测试



---原始邮件---
发件人: "yushe"<notifications@github.com&gt;
发送时间: 2020年9月17日(周四) 中午1:57
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] 为什么我部署后，admin账号没有”系统设置"的功能 (#18)




 
如题，我在您的https://demo.wookteam.com/演示网站，用账号admin/123456,右上角是可以对网站进行基本的设置的，
 但是我部署到服务器上后，右上角却没有“系统设置”这一项，请问这是怎么回事呀
