### ISSUE TITLE
npm install 一直报错~~

### ISSUE THREAD

**Issue by ryan-dream** [kuaifan/wookteam#21]
npm install 一直报错~~npm install 一直报错~~npm install 一直报错~~npm install 一直报错~~

**Comment by kuaifan** [comment]
请科学上网



---原始邮件---
发件人: "ryan-dream"<notifications@github.com&gt;
发送时间: 2020年10月3日(周六) 晚上10:24
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] npm install 一直报错~~ (#21)




 
npm install 一直报错npm install 一直报错npm install 一直报错npm install 一直报错

**Comment by ryan-dream** [comment]
啥意思？？？？ 用科学上网？？ 翻墙？？

**Comment by kuaifan** [comment]
可参考&nbsp;&nbsp;
https://www.jianshu.com/p/95e358084360
https://www.cnblogs.com/xym4869/articles/13262091.html




---原始邮件---
发件人: "ryan-dream"<notifications@github.com&gt;
发送时间: 2020年10月3日(周六) 晚上11:54
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"kuaifan"<aipaw@live.cn&gt;;
主题: Re: [kuaifan/wookteam] npm install 一直报错~~ (#21)




 
啥意思？？？？ 用科学上网？？ 翻墙？？

**Comment by ryan-dream** [comment]
我知道啥问题，解决了，我用centos7.2就好了，以前用centos8.0



---原始邮件---
发件人: "kuaifan"<notifications@github.com&gt;
发送时间: 2020年10月4日(周日) 凌晨3:25
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "ryan-dream"<672061246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [kuaifan/wookteam] npm install 一直报错~~ (#21)




 可参考&amp;nbsp;&amp;nbsp; 
 https://www.jianshu.com/p/95e358084360 
 https://www.cnblogs.com/xym4869/articles/13262091.html 
 
 
 
 
 ---原始邮件--- 
 发件人: "ryan-dream"<notifications@github.com&amp;gt; 
 发送时间: 2020年10月3日(周六) 晚上11:54 
 收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&amp;gt;; 
 抄送: "Comment"<comment@noreply.github.com&amp;gt;;"kuaifan"<aipaw@live.cn&amp;gt;; 
 主题: Re: [kuaifan/wookteam] npm install 一直报错~~ (#21) 
 
 
 
 
   
 啥意思？？？？ 用科学上网？？ 翻墙？？
