### ISSUE TITLE
mysql 的密码是多少，docker安装的，

### ISSUE THREAD

**Issue by advisen** [kuaifan/wookteam#22]
如题
mysql 的密码是多少，docker安装的

**Comment by kuaifan** [comment]
123456



---原始邮件---
发件人: "advisen"<notifications@github.com&gt;
发送时间: 2020年10月10日(周六) 中午12:56
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] mysql 的密码是多少，docker安装的， (#22)




 
如题
 mysql 的密码是多少，docker安装的
