### ISSUE TITLE
部署到阿里云服务器上后，IM即时通讯不可用

### ISSUE THREAD

**Issue by Jade999** [kuaifan/wookteam#23]
您好，我按照docker安装步骤部署在阿里云上，web正常，只是当我用IM即时通讯给别人发消息时，消息传送不过去，提示"错误详情 未连接成功",请问这是什么情况，IM通讯需要单独开放端口嘛

**Comment by kuaifan** [comment]
对的，需要你按教程安装，wookteam不仅只有web服务的



---原始邮件---
发件人: "yushe"<notifications@github.com&gt;
发送时间: 2020年10月10日(周六) 晚上6:39
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] 部署到阿里云服务器上后，IM即时通讯不可用 (#23)




 
您好，我按照docker安装步骤部署在阿里云上，web正常，只是当我用IM即时通讯给别人发消息时，消息传送不过去，提示"错误详情 未连接成功",请问这是什么情况，IM通讯需要单独开放端口嘛
