### ISSUE TITLE
php版本要求？

### ISSUE THREAD

**Issue by HelloZQL** [kuaifan/wookteam#25]
服务器方式部署，对PHP版本有什么要求？

**Comment by kuaifan** [comment]
7.1+



---原始邮件---
发件人: "HelloZQL"<notifications@github.com&gt;
发送时间: 2020年10月20日(周二) 中午1:38
收件人: "kuaifan/wookteam"<wookteam@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [kuaifan/wookteam] php版本要求？ (#25)




 
服务器方式部署，对PHP版本有什么要求？
