### ISSUE TITLE
部署完成后，登录弹出“修改密码”对话框，无法关闭

### ISSUE THREAD

**Issue by unsee** [kuaifan/wookteam#28]
操作系统：centos7.3
部署完成后，登录就弹出修改密码的对话框，修改以后提示重新登录
重新登录后，又弹出修改密码对话框，无法关闭
修改数据库中user表中的changepass字段，从0改为1，无效
修改源代码module目录下的Users.php中的retInfo函数，添加如下代码：
  $userinfo['setpass'] =0；
也无效

**Comment by kuaifan** [comment]
最新版也解决
