### ISSUE TITLE
一些建议和疑问

### ISSUE THREAD

**Issue by shadowfish07** [kuaifan/wookteam#3]
1.登录页UI可以自己设置吗？如果不能，我觉得这个特性挺重要的
2.给项目组内所有成员分配任务比较麻烦，要一个个搜索添加，建议可以一键添加所有成员，或者用勾选列表的方式。
3.默认的两个用户可以删掉吗？其中一个有管理的权限，不过这管理权限好像并不是很大，建议可以把这个管理权限移交给其他用户
4.网站的背景图最好能支持自定义上传
5.下载项目中上传的文件时提示没有php的一个fileinfo的插件，希望可以出一下安装的教程

**Comment by kuye-kuye** [comment]
您好，你的二维码无法显示，在使用过程中遇到一些问题，我以管理员登录上系统之后，团队->添加团队成员，点击确定提示权限不足，页面直接退到登录页面。能留一种联系方式以便于更详细的沟通吗？

**Comment by kuaifan** [comment]
最新提交已经修复，更新即可，或者重新安装。

**Comment by kuaifan** [comment]
这是微信提供的个人二维码呀，什么会识别不了呢

**Comment by kuye-kuye** [comment]
不是识别不了，是加载不出来.....图片加载不出来，不是网速的问题，可能是github的问题吧....

**Comment by kuye-kuye** [comment]
我修改了一些vue页面的代码，然后使用 `./cmd build` 之后再使用 `./cmd start` 启动后，发现页面改动并没有生效，build 里面没有对前端进行重新打包吗？能加一下你的联系方式吗，我接下来也会根据情况对这个项目进行一些二次开发，希望能得到一些您的帮助，万分感谢！

**Comment by kuaifan** [comment]
> 不是识别不了，是加载不出来.....图片加载不出来，不是网速的问题，可能是github的问题吧....

这张
https://github.com/kuaifan/wookteam/blob/master/resources/assets/statics/other/wxqr.jpeg

**Comment by shadowfish07** [comment]
![image](https://user-images.githubusercontent.com/38303418/84379904-21d52c80-ac19-11ea-8adf-669b7b1cd733.png)
宝塔面板，宝塔自带的安装和手动安装都试过，还是不能打开下载页...

**Comment by kuaifan** [comment]
宝塔面板安装教程
https://github.com/kuaifan/wookteam/blob/master/INSTALL-BT.md
