### ISSUE TITLE
<features>[suggestions]: 导出及演示等功能

### ISSUE THREAD

**Issue by freedeaths** [kuaifan/wookteam#5]
试用了一下demo，感觉挺不错的，支持。

请问后续有没有计划加入：

* 一系列的导出功能？比如文档和表格的doc/xls导出、PDF导出、HTML导出，思维导图的xml/json/...导出
* PPT的功能？
* 其它还没有想好

PHP不在我的技术栈上，只能orz

然后貌似有个小的显示Tips的BUG

在思维导图右上角的显示，应该是Enter是同级，Tab是子级吧

脑图的导出我觉得我可以自己魔改一下，应该就是kityminder项目包进来了，这项目本身是支持多种格式导出的

**Comment by kuaifan** [comment]
1.3版本更新了不少知识库的功能
----
新增已完成任务自动归档功能
知识库脑图支持导出PNG/PDF
知识库表格支持导出XLSX/XLS/CSV/TXT
知识库流程图支持导出PNG/PDF
知识库支持锁定功能（锁定后其他会员将无法修改保存文档）
知识库新增分享功能
知识库新增阅读功能
知识库新增修改权限功能（私有文库、成员开放、注册会员）
知识库新增阅读权限功能（私有文库、成员开放、注册会员、完全开放）
> 更新步骤在安装教程底部有
